// Copyright (c) 2026 MakeMyTechnology. All rights reserved.
//
// Package runtime is the PER/UPER encoding support library called by code
// generated by asn1go.
package runtime

// BitString represents an ASN.1 BIT STRING as a byte slice plus a bit length.
// Bits are packed MSB-first in each byte.
type BitString struct {
	Bytes     []byte
	BitLength uint64
}

// OctetString is an alias for a raw byte slice.
type OctetString = []byte

// Enumerated is the base integer type for ASN.1 ENUMERATED values.
type Enumerated = int64

// ObjectIdentifier is a slice of unsigned arcs.
type ObjectIdentifier = []uint64
