// Copyright (c) 2026 MakeMyTechnology. All rights reserved.
//
package codegen

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/dave/jennifer/jen"
	"github.com/mmt/nasgen/pkg/schema"
)

// RuntimeImport is the import path for the NAS runtime package used by all
// generated files. Override via Generator.RuntimeImport.
const DefaultRuntimeImport = "github.com/mmt/nasgen/pkg/runtime"

// Generator orchestrates file generation from a loaded schema Repo.
type Generator struct {
	Repo           *schema.Repo
	OutDir         string
	PackageName    string
	RuntimeImport  string
}

func NewGenerator(repo *schema.Repo, outDir, pkg string) *Generator {
	return &Generator{
		Repo:          repo,
		OutDir:        outDir,
		PackageName:   pkg,
		RuntimeImport: DefaultRuntimeImport,
	}
}

// Generate writes: one file per IE type (ie_<name>.go), one per message
// (msg_<name>.go), plus a dispatcher.go.
func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.OutDir, 0o755); err != nil {
		return err
	}

	// IE type files
	for _, ie := range g.Repo.IETypes {
		f := jen.NewFile(g.PackageName)
		f.HeaderComment("// Code generated by nasgen. DO NOT EDIT.")
		f.ImportName(g.RuntimeImport, "runtime")
		g.generateIEType(f, ie)
		if err := writeFile(filepath.Join(g.OutDir, "ie_"+fileSafe(ie.Name)+".go"), f); err != nil {
			return err
		}
	}

	// Message files
	for _, m := range g.Repo.Messages {
		f := jen.NewFile(g.PackageName)
		f.HeaderComment("// Code generated by nasgen. DO NOT EDIT.")
		f.ImportName(g.RuntimeImport, "runtime")
		g.generateMessage(f, m)
		if err := writeFile(filepath.Join(g.OutDir, "msg_"+fileSafe(m.Name)+".go"), f); err != nil {
			return err
		}
	}

	// Dispatcher
	f := jen.NewFile(g.PackageName)
	f.HeaderComment("// Code generated by nasgen. DO NOT EDIT.")
	f.ImportName(g.RuntimeImport, "runtime")
	g.generateDispatcher(f)
	return writeFile(filepath.Join(g.OutDir, "dispatcher.go"), f)
}

func writeFile(path string, f *jen.File) error {
	fp, err := os.Create(path)
	if err != nil {
		return err
	}
	defer fp.Close()
	return f.Render(fp)
}

func fileSafe(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			out = append(out, r)
		} else if r >= 'A' && r <= 'Z' {
			out = append(out, r+32)
		} else {
			out = append(out, '_')
		}
	}
	return string(out)
}

// --- helpers used across codegen files ---

// qualRuntime returns a qualified ident into the runtime package.
func (g *Generator) qualRuntime(name string) *jen.Statement {
	return jen.Qual(g.RuntimeImport, name)
}

// ieNeedsBitFieldByte returns true if the IE should be encoded as a single
// byte packing multiple bit-fields (most Type 1 / half-octet IEs, and
// bit-field IEs whose total width is 8 bits).
func ieNeedsBitFieldByte(ie *schema.IETypeDef) bool {
	if len(ie.Fields) == 0 {
		return false
	}
	totalBits := 0
	for _, f := range ie.Fields {
		if f.Bits == 0 {
			return false
		}
		totalBits += f.Bits
	}
	return totalBits <= 8
}

// errWrapMsg shortens error-wrapping boilerplate.
func (g *Generator) errWrapMsg(msg, ie string) *jen.Statement {
	return g.qualRuntime("NewDecodeError").Call(
		jen.Lit(msg), jen.Lit(ie), jen.Id("b").Dot("Offset").Call(), jen.Id("err"),
	)
}

// doc prints a line when NASGEN_DEBUG is set.
func doc(format string, args ...interface{}) {
	if os.Getenv("NASGEN_DEBUG") != "" {
		fmt.Fprintf(os.Stderr, "[nasgen] "+format+"\n", args...)
	}
}
