// Copyright (c) 2026 MakeMyTechnology. All rights reserved.
//
package codegen

import (
	"os"
	"path/filepath"

	"github.com/dave/jennifer/jen"
	"github.com/mmt/pfcpgen/pkg/schema"
)

const DefaultRuntimeImport = "github.com/mmt/pfcpgen/pkg/runtime"

type Generator struct {
	Repo          *schema.Repo
	OutDir        string
	PackageName   string
	RuntimeImport string
}

func NewGenerator(repo *schema.Repo, outDir, pkg string) *Generator {
	return &Generator{
		Repo:          repo,
		OutDir:        outDir,
		PackageName:   pkg,
		RuntimeImport: DefaultRuntimeImport,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.OutDir, 0o755); err != nil {
		return err
	}
	for _, ie := range g.Repo.IETypes {
		f := jen.NewFile(g.PackageName)
		f.HeaderComment("// Copyright (c) 2026 MakeMyTechnology. All rights reserved.")
		f.HeaderComment("//")
		f.HeaderComment("// Code generated by pfcpgen. DO NOT EDIT.")
		f.ImportName(g.RuntimeImport, "runtime")
		g.generateIEType(f, ie)
		if err := writeFile(filepath.Join(g.OutDir, "ie_"+FileSafe(ie.Name)+".go"), f); err != nil {
			return err
		}
	}
	for _, m := range g.Repo.Messages {
		f := jen.NewFile(g.PackageName)
		f.HeaderComment("// Copyright (c) 2026 MakeMyTechnology. All rights reserved.")
		f.HeaderComment("//")
		f.HeaderComment("// Code generated by pfcpgen. DO NOT EDIT.")
		f.ImportName(g.RuntimeImport, "runtime")
		g.generateMessage(f, m)
		if err := writeFile(filepath.Join(g.OutDir, "msg_"+FileSafe(m.Name)+".go"), f); err != nil {
			return err
		}
	}
	f := jen.NewFile(g.PackageName)
	f.HeaderComment("// Code generated by pfcpgen. DO NOT EDIT.")
	f.ImportName(g.RuntimeImport, "runtime")
	g.generateDispatcher(f)
	return writeFile(filepath.Join(g.OutDir, "dispatcher.go"), f)
}

func writeFile(path string, f *jen.File) error {
	fp, err := os.Create(path)
	if err != nil {
		return err
	}
	defer fp.Close()
	return f.Render(fp)
}

func (g *Generator) qualRuntime(name string) *jen.Statement {
	return jen.Qual(g.RuntimeImport, name)
}

// isInterface returns true for runtime go_type overrides that are already
// pointer-friendly (FSEID, NodeID, FTEID all use value types here — we return
// false but keep the hook for future interface types).
func (g *Generator) isInterface(string) bool { return false }
