// Copyright (c) 2026 MakeMyTechnology. All rights reserved.
//
// Package codegen emits Go source for ASN.1 modules using github.com/dave/jennifer.
package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/mmt/asn1go/pkg/ast"
	"github.com/mmt/asn1go/pkg/resolver"
)

type Options struct {
	OutDir        string // output directory
	PackageName   string // package name for all generated files (single package)
	ModulePath    string // full module path (for runtime import)
	Encoding      string // "aper" | "uper" | "both"
	GenerateTests bool
}

type Generator struct {
	Reg  *resolver.Registry
	Opts Options
	sets map[string]*resolver.ResolvedObjectSet
	tmpl *templateIndex
}

func New(reg *resolver.Registry, opts Options) *Generator {
	if opts.PackageName == "" {
		opts.PackageName = "asn1gen"
	}
	if opts.Encoding == "" {
		opts.Encoding = "aper"
	}
	return &Generator{Reg: reg, Opts: opts}
}

func (g *Generator) runtimePath() string {
	if g.Opts.ModulePath != "" {
		return g.Opts.ModulePath + "/pkg/runtime"
	}
	return "github.com/mmt/asn1go/pkg/runtime"
}

// Generate writes one Go file per module into OutDir.
func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Opts.OutDir, 0o755); err != nil {
		return err
	}
	// Resolve object sets up-front; they're emitted into whichever module
	// hosts them.
	g.sets = g.Reg.BuildObjectSets()
	g.tmpl = g.buildTemplateIndex()
	for _, m := range g.Reg.Modules {
		if err := g.genModule(m); err != nil {
			return fmt.Errorf("module %s: %w", m.Name, err)
		}
	}
	return nil
}

func (g *Generator) genModule(m *ast.Module) error {
	f := jen.NewFile(g.Opts.PackageName)
	f.HeaderComment("Code generated by asn1go from " + m.Name + ". DO NOT EDIT.")
	f.HeaderComment("ASN.1 module: " + m.Name)

	// Emit object-set-derived typed CHOICE and Entry structs for any object
	// sets declared in this module.
	moduleSets := map[string]*resolver.ResolvedObjectSet{}
	for i := range m.Assignments {
		a := &m.Assignments[i]
		if a.IsObjectSet {
			if rs, ok := g.sets[a.Name]; ok {
				moduleSets[a.Name] = rs
			}
		}
	}
	if len(moduleSets) > 0 {
		g.emitObjectSetChoices(f, moduleSets)
	}

	for i := range m.Assignments {
		a := &m.Assignments[i]
		switch {
		case a.IsClass:
			// Info object classes are not directly emitted as Go types;
			// their fields guide codegen of table-constrained containers.
			continue
		case a.IsObjectSet:
			// Already emitted via emitObjectSetChoices.
			continue
		case a.IsValue:
			g.emitValueConst(f, a)
		case a.Parameterized != nil:
			// Parameterised templates are expanded on usage — no Go type is
			// emitted for the bare template itself.
			continue
		case a.Type != nil:
			g.emitType(f, a.Name, a.Type)
			g.emitCoders(f, a.Name, a.Type)
		}
	}

	outPath := filepath.Join(g.Opts.OutDir, safeFileName(m.Name)+".go")
	return f.Save(outPath)
}

func safeFileName(name string) string {
	return strings.ToLower(strings.ReplaceAll(name, "-", "_"))
}

// --- Value constants ---

func (g *Generator) emitValueConst(f *jen.File, a *ast.Assignment) {
	name := GoName(a.Name)
	switch v := a.Value.(type) {
	case ast.IntegerValue:
		f.Const().Id(name).Op("=").Lit(int(v.Int))
	case ast.BoolValue:
		f.Const().Id(name).Op("=").Lit(v.B)
	case ast.StringValue:
		f.Const().Id(name).Op("=").Lit(v.S)
	case ast.ValueRef:
		// unresolved value reference; emit a comment placeholder.
		f.Comment("// " + a.Name + " = " + v.Name + " (unresolved reference)")
	}
}

// --- Type emission ---

// emitType emits a Go type declaration for the given ASN.1 type assignment.
func (g *Generator) emitType(f *jen.File, name string, t ast.Type) {
	goName := GoName(name)
	switch tt := t.(type) {
	case ast.BooleanType:
		f.Type().Id(goName).Bool()
	case ast.NullType:
		f.Type().Id(goName).Struct()
	case ast.RealType:
		f.Type().Id(goName).Float64()
	case ast.IntegerType:
		f.Type().Id(goName).Int64()
		for _, nn := range tt.NamedNumbers {
			f.Const().Id(goName + GoName(nn.Name)).Id(goName).Op("=").Lit(int(nn.Value))
		}
	case ast.EnumeratedType:
		f.Type().Id(goName).Int64()
		type enumPair struct {
			Name  string
			Value int64
		}
		var pairs []enumPair
		idx := int64(0)
		for _, e := range tt.RootEnums {
			v := e.Value
			if !e.HasValue {
				v = idx
			}
			f.Const().Id(goName + GoName(e.Name)).Id(goName).Op("=").Lit(int(v))
			pairs = append(pairs, enumPair{Name: e.Name, Value: v})
			idx = v + 1
		}
		extStart := int64(len(tt.RootEnums))
		for i, e := range tt.ExtensionEnums {
			v := e.Value
			if !e.HasValue {
				v = extStart + int64(i)
			}
			f.Const().Id(goName + GoName(e.Name)).Id(goName).Op("=").Lit(int(v))
			pairs = append(pairs, enumPair{Name: e.Name, Value: v})
		}
		// Emit a String() method so PrettyJSON / fmt.Println render named values.
		f.Func().Params(jen.Id("m").Id(goName)).Id("String").Params().String().BlockFunc(func(grp *jen.Group) {
			grp.Switch(jen.Int64().Parens(jen.Id("m"))).BlockFunc(func(sw *jen.Group) {
				for _, p := range pairs {
					sw.Case(jen.Lit(int(p.Value))).Block(jen.Return(jen.Lit(p.Name)))
				}
			})
			grp.Return(jen.Qual("fmt", "Sprintf").Call(jen.Lit("unknown("+goName+"=%d)"), jen.Int64().Parens(jen.Id("m"))))
		})
	case ast.BitStringType:
		f.Type().Id(goName).Qual(g.runtimePath(), "BitString")
	case ast.OctetStringType:
		f.Type().Id(goName).Index().Byte()
	case ast.CharStringType:
		f.Type().Id(goName).String()
	case ast.ObjectIdentifierType:
		f.Type().Id(goName).Qual(g.runtimePath(), "ObjectIdentifier")
	case ast.SequenceType:
		g.emitSequence(f, goName, tt)
	case ast.SetType:
		g.emitSequence(f, goName, ast.SequenceType{
			Components: tt.Components, Extensible: tt.Extensible,
			ExtensionAdditions: tt.ExtensionAdditions,
		})
	case ast.SequenceOfType:
		f.Type().Id(goName).Index().Add(g.goType(tt.ElementType))
	case ast.SetOfType:
		f.Type().Id(goName).Index().Add(g.goType(tt.ElementType))
	case ast.ChoiceType:
		g.emitChoice(f, goName, tt)
	case ast.TypeReference:
		if os, ok := g.matchContainerInstantiation(tt); ok {
			f.Type().Id(goName).Index().Id(GoName(os) + "Entry")
			return
		}
		if os, ok := g.matchSingleContainerInstantiation(tt); ok {
			f.Type().Id(goName).Id(GoName(os) + "Entry")
			return
		}
		if g.isUnresolvableTemplateCall(tt) {
			f.Type().Id(goName).Index().Byte()
			return
		}
		f.Type().Id(goName).Add(g.goType(tt))
	case ast.TaggedType:
		g.emitType(f, name, tt.Type)
	case ast.OpenType:
		// Open type erases to a raw byte slice (inner encoding as PER).
		f.Type().Id(goName).Index().Byte()
	default:
		f.Comment("// TODO: " + goName + " (unhandled type)")
	}
}

func (g *Generator) emitSequence(f *jen.File, goName string, seq ast.SequenceType) {
	var fields []jen.Code
	for _, c := range seq.Components {
		fields = append(fields, g.emitComponent(c, false))
	}
	for _, grp := range seq.ExtensionAdditions {
		for _, c := range grp.Components {
			fields = append(fields, g.emitComponent(c, true))
		}
	}
	f.Type().Id(goName).Struct(fields...)
	if seq.Extensible {
		// Marker method recognised by the runtime via interface assertion. It
		// causes encodeSequence to emit the leading extension bit per X.691.
		f.Func().Params(jen.Op("*").Id(goName)).Id("APERExtensible").Params().Block()
	}
}

func (g *Generator) emitComponent(c ast.ComponentType, isExt bool) jen.Code {
	field := jen.Id(GoFieldName(c.Name))
	if c.ComponentsOf != "" {
		// Flatten COMPONENTS OF X by embedding the referenced type.
		return jen.Id(GoName(c.ComponentsOf))
	}
	gt := g.goType(c.Type)
	// If the component type is a container/single-container instantiation we
	// expanded into a typed slice/struct, the SIZE constraint that lived on
	// the template body would otherwise be dropped — propagate it now so the
	// runtime can emit the right length determinant.
	var inheritedConstraint *ast.Constraint
	if tr, ok := c.Type.(ast.TypeReference); ok {
		if _, isContainer := g.matchContainerInstantiation(tr); isContainer {
			inheritedConstraint = g.containerSizeConstraint(tr)
		}
	}
	// If the field type is a named primitive with a constraint, propagate
	// that constraint here so the runtime sees it as a struct tag.
	componentForTag := c
	resolvedNamedType := false
	if _, ok := c.Type.(ast.TypeReference); ok {
		if resolved := g.resolveNamedConstraint(c.Type); resolved != nil {
			componentForTag.Type = resolved
			componentForTag.Constraint = nil
			resolvedNamedType = true
		}
	}
	if c.Optional || c.HasDefault || isExt {
		switch c.Type.(type) {
		case ast.SequenceOfType, ast.SetOfType, ast.OctetStringType:
			field = field.Add(gt)
		default:
			field = field.Op("*").Add(gt)
		}
	} else {
		field = field.Add(gt)
	}
	// If we already resolved the named type's constraint into componentForTag,
	// don't also pass the inherited container constraint — it's the same one.
	extra := inheritedConstraint
	if resolvedNamedType {
		extra = nil
	}
	tag := g.buildAperTagComponent(componentForTag, isExt, extra)
	if tag != "" {
		field = field.Tag(map[string]string{"aper": tag})
	}
	return field
}

func (g *Generator) emitChoice(f *jen.File, goName string, ch ast.ChoiceType) {
	// Struct with Present + one pointer per alternative (root + extensions).
	var fields []jen.Code
	fields = append(fields, jen.Id("Present").Int())
	all := append([]ast.ChoiceAlternative(nil), ch.Alternatives...)
	all = append(all, ch.ExtensionAlternatives...)
	for _, alt := range all {
		gt := g.goType(alt.Type)
		fld := jen.Id(GoFieldName(alt.Name)).Op("*").Add(gt)
		// Propagate the alternative's type-level constraints onto the
		// struct field via an `aper:"..."` tag. Without this, the
		// runtime decoder hits a named int64 (e.g. CauseRadioNetwork)
		// with no bounds and falls back to GetUnconstrainedWhole —
		// which for an extensible ENUMERATED reads a length
		// determinant instead of the correct 1+N-bit index. Concrete
		// failure observed: 2-byte Cause open-type + value like
		// radioNetwork(unknown-local-UE-NGAP-ID=14) → the first data
		// byte happens to encode "length form = 14-bit", the decoder
		// tries to read past end of the 2-byte buffer, and surfaces as
		// "field Value: GetBits: out of data".
		//
		// This mirrors the ENUMERATED-in-component handling in
		// addConstraintReg (ast.EnumeratedType branch) — extended to
		// named TypeReferences by chasing the alias through the
		// registry via resolveNamedConstraint.
		if tag := g.altAperTag(alt.Type); tag != "" {
			fld = fld.Tag(map[string]string{"aper": tag})
		}
		fields = append(fields, fld)
	}
	f.Type().Id(goName).Struct(fields...)

	// Const block for Present values.
	f.Const().DefsFunc(func(grp *jen.Group) {
		grp.Id(goName + "PresentNothing").Op("=").Lit(0)
		for i, alt := range all {
			grp.Id(goName + "Present" + GoName(alt.Name)).Op("=").Lit(i + 1)
		}
	})
	if ch.Extensible {
		f.Func().Params(jen.Op("*").Id(goName)).Id("APERExtensible").Params().Block()
	}
}

// goType maps an ast.Type to a jen.Code for the Go type it corresponds to.
func (g *Generator) goType(t ast.Type) *jen.Statement {
	switch tt := t.(type) {
	case ast.BooleanType:
		return jen.Bool()
	case ast.NullType:
		return jen.Struct()
	case ast.RealType:
		return jen.Float64()
	case ast.IntegerType:
		return jen.Int64()
	case ast.EnumeratedType:
		return jen.Int64()
	case ast.BitStringType:
		return jen.Qual(g.runtimePath(), "BitString")
	case ast.OctetStringType:
		return jen.Index().Byte()
	case ast.CharStringType:
		return jen.String()
	case ast.ObjectIdentifierType:
		return jen.Qual(g.runtimePath(), "ObjectIdentifier")
	case ast.SequenceOfType:
		return jen.Index().Add(g.goType(tt.ElementType))
	case ast.SetOfType:
		return jen.Index().Add(g.goType(tt.ElementType))
	case ast.TypeReference:
		if os, ok := g.matchContainerInstantiation(tt); ok {
			return jen.Index().Id(GoName(os) + "Entry")
		}
		if os, ok := g.matchSingleContainerInstantiation(tt); ok {
			return jen.Id(GoName(os) + "Entry")
		}
		if g.isUnresolvableTemplateCall(tt) {
			return jen.Index().Byte()
		}
		return jen.Id(GoName(tt.TypeName))
	case ast.TaggedType:
		return g.goType(tt.Type)
	case ast.OpenType:
		return jen.Index().Byte()
	case ast.SequenceType:
		// Anonymous inline SEQUENCE — emit as struct literal.
		var fs []jen.Code
		for _, c := range tt.Components {
			fs = append(fs, g.emitComponent(c, false))
		}
		return jen.Struct(fs...)
	case ast.ChoiceType:
		// Anonymous inline CHOICE — map to interface{} for now.
		return jen.Interface()
	}
	return jen.Interface()
}

// buildAperTag constructs the `aper:"..."` struct tag from a component's
// constraints. Only the bounds that matter for PER/UPER are emitted.
func buildAperTag(c ast.ComponentType, isExt bool) string {
	return buildAperTagWithExtra(c, isExt, nil)
}

func buildAperTagWithExtra(c ast.ComponentType, isExt bool, extra *ast.Constraint) string {
	return buildAperTagWithReg(c, isExt, extra, nil)
}

func (g *Generator) buildAperTagComponent(c ast.ComponentType, isExt bool, extra *ast.Constraint) string {
	return buildAperTagWithReg(c, isExt, extra, g.Reg)
}

// altAperTag builds the `aper:"..."` tag contents for a CHOICE
// alternative whose type is `t`. Named types are resolved through the
// registry so that `radioNetwork CauseRadioNetwork` picks up
// CauseRadioNetwork's ENUMERATED root count + extension flag even
// though the alternative itself carries no inline constraint.
func (g *Generator) altAperTag(t ast.Type) string {
	var parts []string
	// Chase named references to their defining type, then reuse the
	// same addConstraintReg path that SEQUENCE components use.
	resolved := t
	if tr, ok := t.(ast.TypeReference); ok {
		if r := g.resolveNamedConstraint(tr); r != nil {
			resolved = r
		}
	}
	// Build a throwaway ComponentType so addConstraintReg sees the
	// type and any inline constraint together — matches what happens
	// for SEQUENCE components in buildAperTagWithReg.
	addConstraintReg(&parts, resolved, nil, g.Reg)
	return strings.Join(parts, ",")
}

func buildAperTagWithReg(c ast.ComponentType, isExt bool, extra *ast.Constraint, reg interface{ ResolveValue(ast.Value) (int64, bool) }) string {
	var parts []string
	addConstraintReg(&parts, c.Type, c.Constraint, reg)
	if extra != nil {
		emitConstraintWithReg(&parts, extra, reg)
	}
	if c.Optional {
		parts = append(parts, "optional")
	}
	if isExt {
		parts = append(parts, "ext")
	}
	return strings.Join(parts, ",")
}

func addConstraint(parts *[]string, t ast.Type, extra *ast.Constraint) {
	addConstraintReg(parts, t, extra, nil)
}

func addConstraintReg(parts *[]string, t ast.Type, extra *ast.Constraint, reg interface{ ResolveValue(ast.Value) (int64, bool) }) {
	var c *ast.Constraint
	switch tt := t.(type) {
	case ast.IntegerType:
		c = tt.Constraint
	case ast.BitStringType:
		c = tt.Constraint
	case ast.OctetStringType:
		c = tt.Constraint
	case ast.CharStringType:
		c = tt.Constraint
	case ast.SequenceOfType:
		c = tt.Constraint
	case ast.SetOfType:
		c = tt.Constraint
	case ast.TypeReference:
		c = tt.Constraint
	case ast.EnumeratedType:
		// Synthesise a value-range tag so the runtime can encode an
		// untagged ENUMERATED struct field with the correct bit width.
		nRoot := int64(len(tt.RootEnums))
		if nRoot > 0 {
			*parts = append(*parts, fmt.Sprintf("valueLB:0"), fmt.Sprintf("valueUB:%d", nRoot-1))
			if tt.Extensible {
				*parts = append(*parts, "valueExt")
			}
		}
	}
	if c != nil {
		emitConstraintWithReg(parts, c, reg)
	}
	if extra != nil {
		emitConstraintWithReg(parts, extra, reg)
	}
}

// resolveNamedConstraint chases a TypeReference through the registry, walking
// any chain of named-type assignments and merging their constraints. This
// lets the codegen tag struct fields with the constraints that live on the
// named type itself (e.g. ProtocolIE-ID := INTEGER (0..65535)) when the field
// declaration carries no per-site constraint.
func (g *Generator) resolveNamedConstraint(t ast.Type) ast.Type {
	tr, ok := t.(ast.TypeReference)
	if !ok {
		return t
	}
	visited := map[string]bool{}
	cur := tr
	for !visited[cur.TypeName] {
		visited[cur.TypeName] = true
		sym, err := g.Reg.Lookup(cur.TypeName)
		if err != nil || sym.Assignment == nil || sym.Assignment.Type == nil {
			break
		}
		next := sym.Assignment.Type
		switch nt := next.(type) {
		case ast.IntegerType, ast.BitStringType, ast.OctetStringType, ast.CharStringType, ast.EnumeratedType, ast.SequenceOfType, ast.SetOfType:
			_ = nt
			return next
		case ast.TypeReference:
			cur = nt
			continue
		}
		break
	}
	return t
}

func emitConstraint(parts *[]string, c *ast.Constraint) {
	emitConstraintWithReg(parts, c, nil)
}

func (g *Generator) emitConstraint(parts *[]string, c *ast.Constraint) {
	emitConstraintWithReg(parts, c, g.Reg)
}

func emitConstraintWithReg(parts *[]string, c *ast.Constraint, reg interface{ ResolveValue(ast.Value) (int64, bool) }) {
	switch c.Kind {
	case ast.ConstraintValue:
		if lb, ok := intOfReg(c.LowerBound, reg); ok {
			*parts = append(*parts, fmt.Sprintf("valueLB:%d", lb))
		}
		if ub, ok := intOfReg(c.UpperBound, reg); ok {
			*parts = append(*parts, fmt.Sprintf("valueUB:%d", ub))
		}
		if c.Extensible {
			*parts = append(*parts, "valueExt")
		}
	case ast.ConstraintSize:
		if c.Inner != nil {
			lb, lbOK := intOfReg(c.Inner.LowerBound, reg)
			ub, ubOK := intOfReg(c.Inner.UpperBound, reg)
			if c.Inner.Kind == ast.ConstraintSingleValue && lbOK && !ubOK {
				ub = lb
				ubOK = true
			}
			if lbOK {
				*parts = append(*parts, fmt.Sprintf("sizeLB:%d", lb))
			}
			if ubOK {
				*parts = append(*parts, fmt.Sprintf("sizeUB:%d", ub))
			}
			if c.Inner.Extensible || c.Extensible {
				*parts = append(*parts, "sizeExt")
			}
		}
	case ast.ConstraintSingleValue:
		if lb, ok := intOfReg(c.LowerBound, reg); ok {
			*parts = append(*parts, fmt.Sprintf("valueLB:%d", lb), fmt.Sprintf("valueUB:%d", lb))
		}
	case ast.ConstraintTable:
		if c.ObjectSet != "" {
			*parts = append(*parts, "openType", "objectSet:"+c.ObjectSet)
			for _, at := range c.AtNotation {
				*parts = append(*parts, "atField:"+at)
			}
		}
	case ast.ConstraintIntersection, ast.ConstraintUnion:
		for _, sub := range c.Operands {
			emitConstraintWithReg(parts, sub, reg)
		}
	}
}

func intOf(v *ast.Value) (int64, bool) {
	return intOfReg(v, nil)
}

func intOfReg(v *ast.Value, reg interface{ ResolveValue(ast.Value) (int64, bool) }) (int64, bool) {
	if v == nil {
		return 0, false
	}
	switch vv := (*v).(type) {
	case ast.IntegerValue:
		return vv.Int, true
	case ast.ValueRef:
		if reg != nil {
			return reg.ResolveValue(vv)
		}
	}
	return 0, false
}
