// Copyright (c) 2026 MakeMyTechnology. All rights reserved.
// db/schemas/billing.go — Charging & Billing DDL (TS 32.290, TS 32.291, TS 32.298)
package schemas

var BillingDDL = []string{
	`CREATE TABLE IF NOT EXISTS charging_profiles (
      id                  INTEGER PRIMARY KEY AUTOINCREMENT,
      name                TEXT UNIQUE NOT NULL,
      charging_method     TEXT NOT NULL CHECK (charging_method IN ('online','offline')) DEFAULT 'offline',
      rating_group        INTEGER NOT NULL CHECK (rating_group > 0),
      meas_volume         INTEGER NOT NULL DEFAULT 1,
      meas_duration       INTEGER NOT NULL DEFAULT 0,
      meas_event          INTEGER NOT NULL DEFAULT 0,
      trg_volume_limit    INTEGER NOT NULL DEFAULT 1,
      trg_time_limit      INTEGER NOT NULL DEFAULT 0,
      trg_session_term    INTEGER NOT NULL DEFAULT 1,
      trg_quota_exhaust   INTEGER NOT NULL DEFAULT 0,
      trg_threshold       INTEGER NOT NULL DEFAULT 0,
      trg_periodic        INTEGER NOT NULL DEFAULT 0,
      vol_quota_ul        INTEGER,
      vol_quota_dl        INTEGER,
      time_quota_sec      INTEGER,
      final_unit_action   TEXT CHECK (final_unit_action IN ('terminate','redirect','restrict') OR final_unit_action IS NULL),
      redirect_url        TEXT,
      vol_threshold_ul    INTEGER,
      vol_threshold_dl    INTEGER,
      time_threshold_sec  INTEGER,
      meas_period_sec     INTEGER
    )`,

	`CREATE TABLE IF NOT EXISTS tariff_plans (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      name            TEXT UNIQUE NOT NULL,
      description     TEXT NOT NULL DEFAULT '',
      charge_type     TEXT NOT NULL DEFAULT 'volume' CHECK (charge_type IN ('volume','time','event','flat')),
      unit_cost       REAL NOT NULL DEFAULT 0.01,
      unit_size       INTEGER NOT NULL DEFAULT 1048576,
      currency        TEXT NOT NULL DEFAULT 'USD',
      free_tier_bytes INTEGER NOT NULL DEFAULT 0,
      free_tier_seconds INTEGER NOT NULL DEFAULT 0,
      peak_multiplier REAL NOT NULL DEFAULT 1.0,
      roaming_multiplier REAL NOT NULL DEFAULT 1.0,
      per_5qi_rates   TEXT NOT NULL DEFAULT '{}',
      per_dnn_rates   TEXT NOT NULL DEFAULT '{}',
      valid_from      TEXT,
      valid_to        TEXT
    )`,

	`CREATE TABLE IF NOT EXISTS cdrs (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      cdr_id          TEXT UNIQUE NOT NULL,
      imsi            TEXT NOT NULL,
      msisdn          TEXT,
      cdr_type        TEXT NOT NULL DEFAULT 'data' CHECK (cdr_type IN ('data','voice','video','sms','event')),
      pdu_session_id  INTEGER,
      dnn             TEXT,
      sst             TEXT,
      sd              TEXT,
      qfi             INTEGER,
      fiveqi          INTEGER,
      resource_type   TEXT,
      start_time      TEXT NOT NULL DEFAULT (datetime('now')),
      end_time        TEXT,
      duration_sec    REAL NOT NULL DEFAULT 0,
      vol_ul_bytes    INTEGER NOT NULL DEFAULT 0,
      vol_dl_bytes    INTEGER NOT NULL DEFAULT 0,
      total_bytes     INTEGER NOT NULL DEFAULT 0,
      pkt_ul          INTEGER NOT NULL DEFAULT 0,
      pkt_dl          INTEGER NOT NULL DEFAULT 0,
      charging_method TEXT NOT NULL DEFAULT 'offline',
      tariff_plan_id  INTEGER,
      rating_status   TEXT NOT NULL DEFAULT 'pending' CHECK (rating_status IN ('pending','rated','invoiced','exported')),
      call_id         TEXT,
      caller_uri      TEXT,
      callee_uri      TEXT,
      media_type      TEXT,
      created_at      TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (tariff_plan_id) REFERENCES tariff_plans(id) ON DELETE SET NULL
    )`,
	`CREATE INDEX IF NOT EXISTS idx_cdr_imsi ON cdrs(imsi)`,
	`CREATE INDEX IF NOT EXISTS idx_cdr_status ON cdrs(rating_status)`,
	`CREATE INDEX IF NOT EXISTS idx_cdr_created ON cdrs(created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_cdrs_tariff_plan_id ON cdrs(tariff_plan_id)`,

	`CREATE TABLE IF NOT EXISTS rated_cdrs (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      cdr_id          TEXT NOT NULL,
      imsi            TEXT NOT NULL,
      charge_amount   REAL NOT NULL DEFAULT 0,
      currency        TEXT NOT NULL DEFAULT 'USD',
      tariff_plan_id  INTEGER,
      unit_count      REAL NOT NULL DEFAULT 0,
      unit_type       TEXT NOT NULL DEFAULT 'MB',
      discount_applied REAL NOT NULL DEFAULT 0,
      tax_amount      REAL NOT NULL DEFAULT 0,
      tax_rate        REAL NOT NULL DEFAULT 0,
      total_amount    REAL NOT NULL DEFAULT 0,
      rated_at        TEXT NOT NULL DEFAULT (datetime('now'))
    )`,
	`CREATE INDEX IF NOT EXISTS idx_rated_imsi ON rated_cdrs(imsi)`,
	`CREATE INDEX IF NOT EXISTS idx_rated_cdrs_cdr_id ON rated_cdrs(cdr_id)`,
	`CREATE INDEX IF NOT EXISTS idx_rated_cdrs_tariff_plan_id ON rated_cdrs(tariff_plan_id)`,

	`CREATE TABLE IF NOT EXISTS balances (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      imsi            TEXT NOT NULL,
      balance_type    TEXT NOT NULL DEFAULT 'main' CHECK (balance_type IN ('main','data','voice','bonus')),
      balance_amount  REAL NOT NULL DEFAULT 0,
      currency        TEXT NOT NULL DEFAULT 'USD',
      credit_limit    REAL NOT NULL DEFAULT 0,
      last_recharge_at TEXT,
      low_balance_threshold REAL NOT NULL DEFAULT 1.0,
      status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','exhausted')),
      UNIQUE(imsi, balance_type)
    )`,

	`CREATE TABLE IF NOT EXISTS payment_transactions (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      imsi            TEXT NOT NULL,
      txn_type        TEXT NOT NULL CHECK (txn_type IN ('recharge','debit','credit','refund')),
      amount          REAL NOT NULL,
      currency        TEXT NOT NULL DEFAULT 'USD',
      balance_before  REAL NOT NULL DEFAULT 0,
      balance_after   REAL NOT NULL DEFAULT 0,
      reference       TEXT,
      created_at      TEXT NOT NULL DEFAULT (datetime('now'))
    )`,

	`CREATE TABLE IF NOT EXISTS invoices (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_number  TEXT UNIQUE NOT NULL,
      imsi            TEXT NOT NULL,
      msisdn          TEXT,
      billing_period_start TEXT NOT NULL,
      billing_period_end   TEXT NOT NULL,
      total_data_charges   REAL NOT NULL DEFAULT 0,
      total_voice_charges  REAL NOT NULL DEFAULT 0,
      total_video_charges  REAL NOT NULL DEFAULT 0,
      total_tax            REAL NOT NULL DEFAULT 0,
      total_amount         REAL NOT NULL DEFAULT 0,
      discount_amount      REAL NOT NULL DEFAULT 0,
      status          TEXT NOT NULL DEFAULT 'generated' CHECK (status IN ('generated','sent','paid','overdue')),
      generated_at    TEXT NOT NULL DEFAULT (datetime('now')),
      due_date        TEXT,
      paid_at         TEXT
    )`,
	`CREATE INDEX IF NOT EXISTS idx_invoice_imsi ON invoices(imsi)`,

	`CREATE TABLE IF NOT EXISTS charging_sessions (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      imsi            TEXT NOT NULL,
      session_id      TEXT UNIQUE NOT NULL,
      service_name    TEXT NOT NULL DEFAULT 'default',
      rating_group    INTEGER NOT NULL DEFAULT 1,
      charging_method TEXT NOT NULL DEFAULT 'offline' CHECK (charging_method IN ('online','offline')),
      status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','interim','final','released')),
      total_volume_ul BIGINT NOT NULL DEFAULT 0,
      total_volume_dl BIGINT NOT NULL DEFAULT 0,
      total_duration  INTEGER NOT NULL DEFAULT 0,
      granted_units   INTEGER,
      used_units      INTEGER,
      created_at      TEXT NOT NULL,
      updated_at      TEXT NOT NULL,
      released_at     TEXT
    )`,
	`CREATE INDEX IF NOT EXISTS idx_chgsess_imsi ON charging_sessions(imsi)`,
	`CREATE INDEX IF NOT EXISTS idx_chgsess_status ON charging_sessions(status)`,
	`CREATE INDEX IF NOT EXISTS idx_chgsess_session ON charging_sessions(session_id)`,

	`CREATE TABLE IF NOT EXISTS quota_grants (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      imsi            TEXT NOT NULL,
      service_name    TEXT NOT NULL DEFAULT 'default',
      granted_units   INTEGER NOT NULL DEFAULT 0,
      used_units      INTEGER NOT NULL DEFAULT 0,
      validity_time   INTEGER NOT NULL DEFAULT 3600,
      granted_at      TEXT NOT NULL DEFAULT (datetime('now')),
      expires_at      TEXT,
      status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','exhausted','expired','revoked'))
    )`,
	`CREATE INDEX IF NOT EXISTS idx_quota_imsi ON quota_grants(imsi)`,
	`CREATE INDEX IF NOT EXISTS idx_quota_status ON quota_grants(status)`,
}
